# Generated by Django 4.2 on 2024-12-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_address_line_1_profile_street_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
