# Generated by Django 5.1.2 on 2024-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
