# Generated by Django 5.1.2 on 2024-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentals', '0003_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
