# Generated by Django 4.2 on 2024-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentals', '0005_remove_beat_slug_beat_beat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='static/audio/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/covers/'),
        ),
    ]
