# Generated by Django 5.1.2 on 2024-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_stripe_metadata_order_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='city',
        ),
    ]
