# Generated by Django 5.1.2 on 2024-10-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentals', '0002_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
